import { StyleSheet } from 'react-native';
import { colors, spacing, typography, shadows } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.bgPrimary,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.md,
    paddingBottom: spacing.xl,
  },
  header: {
    marginBottom: spacing.lg,
  },
  backButton: {
    marginBottom: spacing.md,
  },
  backButtonText: {
    color: colors.primary,
    fontSize: 16,
    fontWeight: '600',
  },
  title: {
    ...typography.h1,
    marginBottom: spacing.xs,
  },
  subtitle: {
    ...typography.caption,
    marginTop: spacing.xs,
  },
  card: {
    backgroundColor: colors.bgSecondary,
    borderRadius: 16,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.md,
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: spacing.md,
  },
  cardHeaderLeft: {
    flex: 1,
  },
  cardTitle: {
    ...typography.h3,
    marginBottom: spacing.sm,
  },
  scheduleInfo: {
    marginTop: spacing.xs,
  },
  scheduleDays: {
    color: colors.textSecondary,
    fontSize: 14,
    marginBottom: spacing.xs,
  },
  scheduleTime: {
    color: colors.accent,
    fontSize: 14,
  },
  noScheduleText: {
    color: colors.warning,
    fontSize: 14,
    marginTop: spacing.xs,
  },
  configButton: {
    backgroundColor: colors.bgTertiary,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  configButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  dateContainer: {
    marginBottom: spacing.sm,
  },
  dateInput: {
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: spacing.md,
    color: colors.textPrimary,
    fontSize: 16,
    marginBottom: spacing.xs,
  },
  dateInputTraining: {
    borderColor: colors.primary,
    borderWidth: 2,
  },
  dateInputNotTraining: {
    borderColor: colors.warning,
    borderWidth: 2,
  },
  dateInputCancelled: {
    borderColor: colors.error,
    borderWidth: 2,
    backgroundColor: `${colors.error}15`,
  },
  dateDisplay: {
    color: colors.textSecondary,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: spacing.md,
  },
  dateWarning: {
    color: colors.warning,
    fontSize: 12,
    marginTop: spacing.xs,
  },
  dateSuccess: {
    color: colors.success,
    fontSize: 12,
    marginTop: spacing.xs,
  },
  dateNavButtons: {
    flexDirection: 'row',
    gap: spacing.sm,
  },
  navButton: {
    flex: 1,
    backgroundColor: colors.bgTertiary,
    padding: spacing.md,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  navButtonText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  statsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  quickActions: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  quickActionButton: {
    backgroundColor: colors.bgTertiary,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border,
  },
  quickActionText: {
    color: colors.textPrimary,
    fontSize: 12,
    fontWeight: '600',
  },
  searchInput: {
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: spacing.md,
    color: colors.textPrimary,
    fontSize: 16,
    marginBottom: spacing.md,
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: 14,
    textAlign: 'center',
    padding: spacing.lg,
  },
  playerRow: {
    backgroundColor: colors.bgTertiary,
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  playerRowPresent: {
    borderColor: colors.success,
    borderWidth: 2,
    backgroundColor: 'rgba(34, 197, 94, 0.1)',
  },
  playerRowAbsent: {
    borderColor: colors.error,
    borderWidth: 2,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
  },
  playerInfo: {
    marginBottom: spacing.sm,
  },
  playerName: {
    ...typography.body,
    fontWeight: '600',
  },
  playerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
  },
  statusButtons: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  statusButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: colors.bgSecondary,
    borderWidth: 2,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusButtonActive: {
    borderWidth: 2,
  },
  statusButtonPresent: {
    backgroundColor: colors.success,
    borderColor: colors.success,
  },
  statusButtonAbsent: {
    backgroundColor: colors.error,
    borderColor: colors.error,
  },
  statusButtonText: {
    fontSize: 20,
    color: colors.textMuted,
  },
  statusButtonTextActive: {
    color: '#fff',
  },
  signatureInput: {
    flex: 1,
    backgroundColor: colors.bgSecondary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    padding: spacing.sm,
    color: colors.textPrimary,
    fontSize: 14,
  },
  saveButton: {
    backgroundColor: colors.primary,
    padding: spacing.md,
    borderRadius: 12,
    alignItems: 'center',
    marginTop: spacing.md,
  },
  saveButtonDisabled: {
    opacity: 0.6,
  },
  saveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.bgSecondary,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: '90%',
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  modalTitle: {
    ...typography.h2,
  },
  modalClose: {
    fontSize: 24,
    color: colors.textMuted,
    fontWeight: '300',
  },
  modalScroll: {
    padding: spacing.md,
  },
  modalSubtitle: {
    ...typography.caption,
    marginBottom: spacing.lg,
    lineHeight: 20,
  },
  monthNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
    paddingHorizontal: spacing.sm,
  },
  monthNavButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.bgTertiary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  monthNavButtonText: {
    color: colors.textPrimary,
    fontSize: 20,
    fontWeight: '600',
  },
  monthYearContainer: {
    flex: 1,
    alignItems: 'center',
  },
  monthYearText: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  calendarContainer: {
    marginBottom: spacing.lg,
  },
  calendarHeader: {
    flexDirection: 'row',
    marginBottom: spacing.sm,
  },
  calendarHeaderCell: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: spacing.xs,
  },
  calendarHeaderText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  calendarCell: {
    width: '13.5%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  calendarDayButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'transparent',
    borderWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  calendarDayButtonOtherMonth: {
    opacity: 0.3,
  },
  calendarDayButtonSelected: {
    backgroundColor: '#1a73e8',
  },
  calendarDayButtonActive: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  calendarDayText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '500',
  },
  calendarDayTextOtherMonth: {
    color: colors.textMuted,
    opacity: 0.5,
  },
  calendarDayTextSelected: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 15,
  },
  modifiedIndicator: {
    position: 'absolute',
    bottom: 2,
    left: '50%',
    marginLeft: -8,
    width: 16,
    height: 2,
    backgroundColor: colors.warning,
    borderRadius: 1,
  },
  calendarDayButtonCancelled: {
    backgroundColor: colors.error,
    opacity: 0.7,
  },
  calendarDayButtonAdded: {
    backgroundColor: colors.success,
  },
  calendarDayButtonSelectedDate: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  calendarDayButtonTimeSelected: {
    borderWidth: 3,
    borderColor: colors.primary,
    borderStyle: 'dashed',
  },
  calendarDayTextCancelled: {
    color: '#fff',
    textDecorationLine: 'line-through',
  },
  calendarDayTextAdded: {
    color: '#fff',
    fontWeight: '700',
  },
  cancelledIndicator: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelledIndicatorText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
  },
  addedIndicator: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addedIndicatorText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  scheduleSummary: {
    backgroundColor: colors.bgTertiary,
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cancelledDaysText: {
    color: colors.error,
    fontSize: 13,
    fontWeight: '600',
    marginTop: spacing.xs,
  },
  addedDaysText: {
    color: colors.success,
    fontSize: 13,
    fontWeight: '600',
    marginTop: spacing.xs,
  },
  dayOfWeekSelector: {
    backgroundColor: colors.bgTertiary,
    borderRadius: 20,
    padding: spacing.lg,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.border,
    ...shadows.md,
  },
  selectorHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  selectorIconContainer: {
    width: 48,
    height: 48,
    borderRadius: 16,
    backgroundColor: `${colors.accent}20`,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  selectorIcon: {
    fontSize: 24,
  },
  selectorHeaderText: {
    flex: 1,
  },
  selectorTitle: {
    ...typography.h3,
    fontSize: 18,
    marginBottom: spacing.xs,
  },
  selectorSubtitle: {
    ...typography.caption,
    color: colors.textMuted,
    fontSize: 13,
    lineHeight: 18,
  },
  dayOfWeekGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  dayOfWeekButton: {
    width: '13.5%',
    aspectRatio: 1,
    backgroundColor: colors.bgSecondary,
    borderRadius: 16,
    borderWidth: 2.5,
    borderColor: colors.border,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
    overflow: 'hidden',
    ...shadows.sm,
  },
  dayOfWeekButtonSelected: {
    backgroundColor: '#1a73e8',
    borderColor: '#1a73e8',
    borderWidth: 3,
    transform: [{ scale: 1.08 }],
    ...shadows.lg,
  },
  dayOfWeekGlow: {
    position: 'absolute',
    top: -10,
    right: -10,
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    opacity: 0.6,
  },
  dayOfWeekButtonText: {
    color: colors.textPrimary,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  dayOfWeekButtonTextSelected: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 14,
  },
  dayOfWeekCheckmarkContainer: {
    position: 'absolute',
    top: 6,
    right: 6,
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    ...shadows.sm,
  },
  dayOfWeekCheckmark: {
    color: '#fff',
    fontSize: 11,
    fontWeight: '900',
  },
  selectedDaysPreview: {
    backgroundColor: `${colors.success}15`,
    borderRadius: 12,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: `${colors.success}30`,
    marginTop: spacing.sm,
  },
  selectedDaysPreviewText: {
    color: colors.success,
    fontSize: 13,
    fontWeight: '600',
    textAlign: 'center',
  },
  dayTimeContainer: {
    backgroundColor: colors.bgTertiary,
    borderRadius: 12,
    padding: spacing.md,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  dayTimeHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  dayTimeTitle: {
    ...typography.h3,
    fontSize: 16,
  },
  dayTimeSubtitle: {
    ...typography.caption,
    color: colors.textMuted,
    fontSize: 12,
    marginBottom: spacing.md,
  },
  removeDayButton: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: 8,
    backgroundColor: colors.error,
  },
  removeDayButtonText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '600',
  },
  selectedDaysText: {
    color: colors.success,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: spacing.lg,
    textAlign: 'center',
  },
  timeContainer: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  timeInputGroup: {
    flex: 1,
  },
  timeLabel: {
    color: colors.textSecondary,
    fontSize: 14,
    fontWeight: '600',
    marginBottom: spacing.xs,
  },
  timeInput: {
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    padding: spacing.md,
    color: colors.textPrimary,
    fontSize: 16,
  },
  modalSaveButton: {
    backgroundColor: colors.primary,
    padding: spacing.md,
    borderRadius: 12,
    alignItems: 'center',
    marginBottom: spacing.md,
  },
  modalSaveButtonDisabled: {
    opacity: 0.6,
  },
  modalSaveButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '700',
  },
});

