import { StyleSheet } from 'react-native';
import { colors, spacing, radius, typography, shadow, alpha } from '../../ui/tokens';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  errorText: {
    color: colors.error,
    fontSize: 16,
    textAlign: 'center',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.md,
    paddingBottom: spacing.md,
    backgroundColor: colors.bgSecondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  backBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.sm,
  },
  headerContent: {
    flex: 1,
  },
  headerTitle: {
    ...typography.h2,
    marginBottom: spacing.xs,
  },
  headerSubtitle: {
    ...typography.body,
    fontSize: 12,
    color: colors.textMuted,
  },
  moreBtn: {
    width: 40,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tabContent: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    padding: spacing.md,
    paddingBottom: 100, // Space for bottom action bar
  },
  summaryGrid: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.md,
  },
  nextSessionCard: {
    backgroundColor: colors.bgSecondary,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  nextSessionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
    gap: spacing.sm,
  },
  nextSessionTitle: {
    ...typography.h3,
    fontSize: 16,
  },
  nextSessionDate: {
    ...typography.body,
    fontSize: 18,
    fontWeight: '700',
    marginBottom: spacing.xs,
  },
  nextSessionTime: {
    ...typography.body,
    color: colors.textMuted,
  },
  tabView: {
    flex: 1,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgSecondary,
    borderRadius: radius.sm,
    paddingHorizontal: spacing.md,
    margin: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  searchIcon: {
    marginRight: spacing.sm,
  },
  searchInput: {
    flex: 1,
    ...typography.body,
    paddingVertical: spacing.md,
    color: colors.textPrimary,
  },
  clearBtn: {
    padding: spacing.xs,
  },
  listContent: {
    padding: spacing.md,
    paddingBottom: 100,
  },
  emptyListContent: {
    flex: 1,
    justifyContent: 'center',
    paddingBottom: 100,
  },
  playerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgSecondary,
    borderRadius: radius.sm,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  playerAvatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: colors.primary,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: spacing.md,
  },
  playerAvatarText: {
    fontSize: 18,
    fontWeight: '800',
    color: '#ffffff',
  },
  playerInfo: {
    flex: 1,
  },
  playerName: {
    ...typography.body,
    fontWeight: '700',
    marginBottom: spacing.xs,
  },
  playerMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
    marginBottom: spacing.xs,
  },
  playerPhone: {
    ...typography.caption,
    color: colors.textMuted,
  },
  playerBadges: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.xs,
    marginTop: spacing.xs,
  },
  badge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: alpha(colors.success, 0.15),
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: alpha(colors.success, 0.3),
    gap: 4,
  },
  badgePassword: {
    backgroundColor: alpha(colors.warning, 0.15),
    borderColor: alpha(colors.warning, 0.3),
  },
  badgeText: {
    ...typography.caption,
    fontSize: 10,
    fontFamily: 'monospace',
  },
  playerFee: {
    alignItems: 'flex-end',
    marginRight: spacing.sm,
  },
  playerFeeAmount: {
    ...typography.body,
    fontWeight: '800',
    color: colors.primary,
  },
  playerFeeLabel: {
    ...typography.caption,
    color: colors.textMuted,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: spacing.xl * 2,
    paddingHorizontal: spacing.lg,
  },
  emptyText: {
    ...typography.body,
    fontWeight: '700',
    marginTop: spacing.md,
    marginBottom: spacing.xs,
  },
  emptySubtext: {
    ...typography.caption,
    color: colors.textMuted,
    textAlign: 'center',
  },
  paymentSummary: {
    flexDirection: 'row',
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  paymentSummaryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: spacing.md,
    marginBottom: spacing.lg,
  },
  paymentSummaryCard: {
    flex: 1,
    minWidth: '30%',
    backgroundColor: colors.bgSecondary,
    borderRadius: radius.md,
    padding: spacing.md,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  paymentSummaryValue: {
    ...typography.h3,
    marginTop: spacing.xs,
    marginBottom: spacing.xs,
  },
  paymentSummaryLabel: {
    ...typography.caption,
    fontSize: 11,
    color: colors.textMuted,
    textAlign: 'center',
  },
  filterChips: {
    flexDirection: 'row',
    gap: spacing.sm,
    marginBottom: spacing.lg,
    flexWrap: 'wrap',
  },
  filterChip: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.xs,
    borderRadius: radius.sm,
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.border,
  },
  filterChipActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  filterChipText: {
    ...typography.body,
    fontSize: 13,
    fontWeight: '600',
    color: colors.textMuted,
  },
  filterChipTextActive: {
    color: '#ffffff',
  },
  paymentsScrollContent: {
    padding: spacing.md,
    paddingBottom: 100, // Space for bulk action bar
  },
  paymentsListContent: {
    padding: spacing.md,
    paddingBottom: 100, // Space for bulk action bar
  },
  section: {
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    ...typography.h3,
    marginBottom: spacing.md,
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: colors.bgSecondary,
    borderRadius: radius.sm,
    padding: spacing.md,
    marginBottom: spacing.sm,
    borderWidth: 1,
    borderColor: colors.border,
  },
  paymentInfo: {
    flex: 1,
  },
  paymentPlayerName: {
    ...typography.body,
    fontWeight: '700',
    marginBottom: spacing.xs,
  },
  paymentMeta: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.sm,
    flexWrap: 'wrap',
  },
  paymentStatusBadge: {
    paddingHorizontal: spacing.xs,
    paddingVertical: 2,
    borderRadius: radius.sm,
    backgroundColor: alpha(colors.info, 0.15),
    borderWidth: 1,
    borderColor: alpha(colors.info, 0.3),
  },
  paymentStatusBadgePaid: {
    backgroundColor: alpha(colors.success, 0.15),
    borderColor: alpha(colors.success, 0.3),
  },
  paymentStatusBadgePartial: {
    backgroundColor: alpha(colors.warning, 0.15),
    borderColor: alpha(colors.warning, 0.3),
  },
  paymentStatusBadgeUnpaid: {
    backgroundColor: alpha(colors.error, 0.15),
    borderColor: alpha(colors.error, 0.3),
  },
  paymentStatusBadgeLate: {
    backgroundColor: alpha(colors.error, 0.25),
    borderColor: colors.error,
  },
  paymentStatusText: {
    ...typography.caption,
    fontSize: 10,
    fontWeight: '700',
    color: colors.info,
  },
  paymentStatusTextPaid: {
    color: colors.success,
  },
  paymentStatusTextPartial: {
    color: colors.warning,
  },
  paymentStatusTextUnpaid: {
    color: colors.error,
  },
  paymentStatusTextLate: {
    color: colors.error,
  },
  paymentDueDate: {
    ...typography.caption,
    fontSize: 11,
    color: colors.textMuted,
  },
  paymentMonth: {
    ...typography.caption,
    color: colors.textMuted,
  },
  paymentAmount: {
    alignItems: 'flex-end',
  },
  paymentOutstanding: {
    ...typography.body,
    fontWeight: '800',
    color: colors.error,
    marginBottom: spacing.xs,
  },
  paymentOutstandingLate: {
    color: colors.error,
  },
  paymentDetail: {
    ...typography.caption,
    fontSize: 11,
    color: colors.textMuted,
  },
  paymentsActionBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgSecondary,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    gap: spacing.sm,
    ...shadow.lg,
  },
  bulkActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    gap: spacing.xs,
  },
  bulkActionBtnPrimary: {
    backgroundColor: colors.primary,
  },
  bulkActionBtnSecondary: {
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.border,
  },
  bulkActionText: {
    ...typography.body,
    fontSize: 13,
    fontWeight: '700',
    color: '#ffffff',
  },
  bulkActionTextSecondary: {
    color: colors.textPrimary,
  },
  scheduleCard: {
    backgroundColor: colors.bgSecondary,
    borderRadius: radius.md,
    padding: spacing.lg,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  scheduleHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.md,
    gap: spacing.sm,
  },
  scheduleTitle: {
    ...typography.h3,
  },
  scheduleDays: {
    gap: spacing.sm,
  },
  scheduleDay: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  scheduleDayName: {
    ...typography.body,
    fontWeight: '700',
  },
  scheduleDayTime: {
    ...typography.body,
    color: colors.textMuted,
  },
  primaryActionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: radius.md,
    paddingVertical: spacing.md,
    gap: spacing.sm,
  },
  primaryActionText: {
    ...typography.body,
    fontWeight: '700',
    color: '#ffffff',
  },
  secondaryActionBtn: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.bgTertiary,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  addPlayerBtn: {
    width: 48,
    height: 48,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: alpha(colors.primary, 0.15),
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: alpha(colors.primary, 0.3),
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.md,
    gap: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  menuItemDanger: {
    borderBottomWidth: 0,
  },
  menuItemText: {
    flex: 1,
    ...typography.body,
  },
  menuItemTextDanger: {
    color: colors.error,
  },
  formScroll: {
    maxHeight: 400,
  },
  inputLabel: {
    ...typography.body,
    fontWeight: '700',
    marginBottom: spacing.sm,
    marginTop: spacing.md,
  },
  input: {
    backgroundColor: colors.bgTertiary,
    borderRadius: radius.sm,
    padding: spacing.md,
    ...typography.body,
    color: colors.textPrimary,
    borderWidth: 1,
    borderColor: colors.border,
  },
  textArea: {
    height: 100,
    textAlignVertical: 'top',
    paddingTop: spacing.md,
  },
  inputHint: {
    ...typography.caption,
    color: colors.textMuted,
    marginTop: spacing.xs,
    marginBottom: spacing.sm,
  },
  infoBox: {
    backgroundColor: alpha(colors.success, 0.1),
    padding: spacing.md,
    borderRadius: radius.sm,
    borderWidth: 1,
    borderColor: alpha(colors.success, 0.3),
    marginTop: spacing.md,
  },
  infoBoxText: {
    ...typography.body,
    fontSize: 13,
    color: colors.success,
    fontWeight: '600',
  },
  formFooter: {
    flexDirection: 'row',
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: spacing.md,
  },
  formBtn: {
    flex: 1,
    padding: spacing.md,
    borderRadius: radius.sm,
    alignItems: 'center',
  },
  formBtnCancel: {
    backgroundColor: colors.bgTertiary,
    borderWidth: 1,
    borderColor: colors.border,
  },
  formBtnPrimary: {
    backgroundColor: colors.primary,
  },
  formBtnDisabled: {
    opacity: 0.5,
  },
  formBtnText: {
    ...typography.body,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  formBtnTextPrimary: {
    color: '#ffffff',
  },
  testModeWarning: {
    backgroundColor: alpha(colors.warning, 0.15),
    padding: spacing.md,
    borderRadius: radius.sm,
    marginTop: spacing.md,
    borderWidth: 2,
    borderColor: colors.warning,
  },
  testModeTitle: {
    ...typography.body,
    fontWeight: '800',
    color: colors.warning,
    marginBottom: spacing.sm,
  },
  testModeText: {
    ...typography.body,
    fontSize: 13,
    color: colors.textPrimary,
    lineHeight: 20,
    marginTop: spacing.xs,
  },
  resultBox: {
    padding: spacing.md,
    borderRadius: radius.sm,
    marginTop: spacing.md,
    borderWidth: 2,
  },
  resultBoxSuccess: {
    backgroundColor: alpha(colors.success, 0.1),
    borderColor: colors.success,
  },
  resultBoxError: {
    backgroundColor: alpha(colors.error, 0.1),
    borderColor: colors.error,
  },
  resultTitle: {
    ...typography.body,
    fontWeight: '700',
    marginBottom: spacing.sm,
  },
  resultTitleSuccess: {
    color: colors.success,
  },
  resultTitleError: {
    color: colors.error,
  },
  resultText: {
    ...typography.body,
    fontSize: 14,
    color: colors.textSecondary,
    marginTop: spacing.xs,
  },
  bottomActionBarWithShadow: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.bgSecondary,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    paddingHorizontal: spacing.md,
    paddingTop: spacing.md,
    gap: spacing.sm,
    ...shadow.lg,
  },
});
