import { StyleSheet } from 'react-native';
import { colors, spacing, typography, shadows } from '../theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 12,
    paddingTop: 50,
    backgroundColor: colors.bgSecondary,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
  },
  logoutButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.bgTertiary || 'rgba(255, 255, 255, 0.1)',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: colors.border || 'rgba(255, 255, 255, 0.2)',
  },
  logoutText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '600',
  },
  scrollView: {
    flex: 1,
  },
  welcomeCard: {
    backgroundColor: colors.bgSecondary,
    padding: 14,
    margin: 10,
    marginBottom: 8,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  welcomeTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 12,
    letterSpacing: 0.3,
  },
  welcomeText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 8,
  },
  welcomeInfo: {
    gap: 8,
  },
  welcomeInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  welcomeInfoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
    marginRight: 8,
    minWidth: 60,
  },
  welcomeInfoValue: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  welcomeInfoValueContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  welcomeInfoPhone: {
    fontSize: 12,
    fontWeight: '500',
    color: colors.textMuted,
    marginLeft: 4,
  },
  sportIcon: {
    fontSize: 16,
    marginRight: 6,
  },
  badgeContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  badge: {
    backgroundColor: colors.bgTertiary,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: colors.border,
  },
  badgeText: {
    color: colors.textPrimary,
    fontSize: 11,
    fontWeight: '600',
  },
  statsContainer: {
    flexDirection: 'row',
    padding: 10,
    gap: 8,
    marginBottom: 8,
  },
  statCard: {
    flex: 1,
    backgroundColor: colors.bgSecondary,
    borderRadius: 14,
    padding: 14,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: colors.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 5,
  },
  statIconContainer: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.primary + '25',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 10,
    borderWidth: 2,
    borderColor: colors.primary + '40',
  },
  statIconContainerSuccess: {
    backgroundColor: '#10b98125',
    borderColor: '#10b98140',
  },
  statIconContainerError: {
    backgroundColor: '#ef444425',
    borderColor: '#ef444440',
  },
  statIcon: {
    fontSize: 20,
  },
  statValue: {
    fontSize: 22,
    fontWeight: '800',
    color: colors.primary,
    marginBottom: 5,
    letterSpacing: -0.5,
  },
  statValueSuccess: {
    color: '#10b981',
  },
  statValueError: {
    color: '#ef4444',
  },
  statLabel: {
    fontSize: 11,
    color: colors.textMuted,
    fontWeight: '600',
    textAlign: 'center',
    letterSpacing: 0.3,
  },
  tabContainer: {
    flexDirection: 'row',
    backgroundColor: colors.bgSecondary,
    paddingHorizontal: 10,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    gap: 8,
  },
  tab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: colors.bgTertiary,
    gap: 6,
  },
  tabActive: {
    backgroundColor: colors.primary + '20',
    borderWidth: 1,
    borderColor: colors.primary,
  },
  tabIcon: {
    fontSize: 16,
  },
  tabIconActive: {
    fontSize: 18,
  },
  tabText: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textMuted,
  },
  tabTextActive: {
    color: colors.primary,
    fontWeight: '700',
  },
  card: {
    backgroundColor: colors.bgSecondary,
    borderRadius: 14,
    padding: 14,
    margin: 10,
    marginTop: 0,
    borderWidth: 1,
    borderColor: colors.border,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 6,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.textPrimary,
    marginBottom: 12,
    letterSpacing: 0.2,
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  infoLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textSecondary,
    marginRight: 6,
    width: 70,
  },
  infoValue: {
    fontSize: 12,
    color: colors.textPrimary,
    flex: 1,
  },
  notesContainer: {
    marginTop: 6,
  },
  notesText: {
    fontSize: 11,
    color: colors.textMuted,
    marginTop: 3,
    lineHeight: 16,
  },
  paymentRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  paymentInfo: {
    flex: 1,
  },
  paymentMonth: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
    marginBottom: 3,
  },
  paymentAmount: {
    fontSize: 11,
    color: colors.textMuted,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
  },
  statusBadgepaid: {
    backgroundColor: '#10b98120',
  },
  statusBadgepartial: {
    backgroundColor: '#f59e0b20',
  },
  statusBadgeunpaid: {
    backgroundColor: '#ef444420',
  },
  statusText: {
    fontSize: 10,
    fontWeight: '600',
  },
  attendanceStats: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginBottom: 12,
    paddingVertical: 10,
    backgroundColor: colors.bgTertiary,
    borderRadius: 8,
  },
  attendanceStat: {
    alignItems: 'center',
  },
  attendanceStatValue: {
    fontSize: 18,
    fontWeight: '800',
    color: colors.primary,
    marginBottom: 3,
  },
  attendanceStatLabel: {
    fontSize: 10,
    color: colors.textMuted,
    textTransform: 'uppercase',
  },
  attendanceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: 6,
    marginBottom: 6,
  },
  attendancePresent: {
    backgroundColor: '#10b98120',
  },
  attendanceAbsent: {
    backgroundColor: '#ef444420',
  },
  attendanceDate: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  attendanceStatus: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.textPrimary,
  },
  loader: {
    marginVertical: 20,
  },
  errorText: {
    color: colors.error,
    fontSize: 12,
    textAlign: 'center',
    margin: 15,
  },
  emptyText: {
    color: colors.textMuted,
    fontSize: 11,
    textAlign: 'center',
    padding: 15,
  },
  selectedDaysPreview: {
    backgroundColor: colors.success + '20',
    borderRadius: 8,
    padding: 8,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: colors.success,
  },
  selectedDaysPreviewText: {
    color: colors.success,
    fontSize: 11,
    fontWeight: '600',
  },
  monthNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    paddingHorizontal: 6,
  },
  monthNavButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.bgTertiary,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  monthNavButtonText: {
    color: colors.textPrimary,
    fontSize: 16,
    fontWeight: '600',
  },
  monthYearContainer: {
    flex: 1,
    alignItems: 'center',
  },
  monthYearText: {
    color: colors.textPrimary,
    fontSize: 18,
    fontWeight: '700',
  },
  calendarContainer: {
    marginBottom: spacing.lg,
  },
  calendarHeader: {
    flexDirection: 'row',
    marginBottom: spacing.sm,
  },
  calendarHeaderCell: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: spacing.xs,
  },
  calendarHeaderText: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '600',
    textTransform: 'uppercase',
  },
  calendarGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
  },
  calendarCell: {
    width: '13.5%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  calendarDayButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'transparent',
    borderWidth: 0,
    justifyContent: 'center',
    alignItems: 'center',
    position: 'relative',
  },
  calendarDayButtonOtherMonth: {
    opacity: 0.3,
  },
  calendarDayButtonSelected: {
    backgroundColor: '#1a73e8',
  },
  calendarDayButtonPast: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: colors.textMuted,
    opacity: 0.6,
  },
  calendarDayButtonCancelled: {
    backgroundColor: colors.error,
    opacity: 0.7,
  },
  calendarDayButtonAdded: {
    backgroundColor: colors.success,
  },
  calendarDayButtonSelectedDate: {
    borderWidth: 2,
    borderColor: colors.primary,
  },
  calendarDayText: {
    color: colors.textPrimary,
    fontSize: 14,
    fontWeight: '500',
  },
  calendarDayTextOtherMonth: {
    color: colors.textMuted,
    opacity: 0.5,
  },
  calendarDayTextSelected: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 15,
  },
  calendarDayTextPast: {
    color: colors.textMuted,
    fontWeight: '500',
    fontSize: 14,
  },
  calendarDayTextCancelled: {
    color: '#fff',
    textDecorationLine: 'line-through',
  },
  calendarDayTextAdded: {
    color: '#fff',
    fontWeight: '700',
  },
  cancelledIndicator: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  cancelledIndicatorText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: '800',
  },
  addedIndicator: {
    position: 'absolute',
    top: 2,
    right: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  addedIndicatorText: {
    color: '#fff',
    fontSize: 12,
    fontWeight: '800',
  },
  pastDateIndicator: {
    position: 'absolute',
    top: 2,
    left: 2,
    width: 16,
    height: 16,
    borderRadius: 8,
    backgroundColor: colors.textMuted,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pastDateIndicatorText: {
    color: colors.bgPrimary,
    fontSize: 10,
    fontWeight: '800',
  },
  pastDateLabel: {
    color: colors.textMuted,
    fontSize: 12,
    fontWeight: '500',
  },
  selectedDateTimeContainer: {
    backgroundColor: colors.bgTertiary,
    borderRadius: 12,
    padding: spacing.md,
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  selectedDateTitle: {
    ...typography.h3,
    fontSize: 16,
    marginBottom: spacing.md,
    color: colors.primary,
  },
  defaultTimeContainer: {
    backgroundColor: colors.bgTertiary,
    borderRadius: 12,
    padding: spacing.md,
    marginTop: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  defaultTimeTitle: {
    ...typography.h3,
    fontSize: 16,
    marginBottom: spacing.xs,
  },
  defaultTimeSubtitle: {
    ...typography.caption,
    color: colors.textMuted,
    marginBottom: spacing.md,
  },
  timeDisplayContainer: {
    flexDirection: 'row',
    gap: spacing.md,
  },
  timeSlot: {
    flex: 1,
    backgroundColor: colors.bgSecondary,
    borderRadius: 12,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.border,
  },
  timeSlotLabel: {
    ...typography.caption,
    color: colors.textMuted,
    marginBottom: spacing.xs,
    fontSize: 12,
  },
  timeSlotValue: {
    ...typography.h3,
    fontSize: 18,
    color: colors.primary,
    fontWeight: '700',
  },
  timeSlotValuePast: {
    color: '#000000',
  },
});

